<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DataLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataLogRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('date' => 'DESC'));
    }
}
