<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Spieler;

/**
 * ErgebnisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErgebnisRepository extends EntityRepository {

    public function findByBegegnungOrdered(Begegnung $begegnung) {
        return $this->getEntityManager()
                        ->createQuery('SELECT e FROM AppBundle:Ergebnis e 
                JOIN e.spielArt sa
                WHERE e.begegnung=' . $begegnung->getId() . " ORDER BY sa.nummer ASC")
                        ->getResult();
    }

    public function findBySpieler(Spieler $spieler) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('e')
                ->from('AppBundle:Ergebnis', 'e')
                ->orderBy('e.id', 'DESC')
                ->where($qb->expr()->orx(
                                $qb->expr()->eq('e.spieler1_1', '?1'), 
                         $qb->expr()->eq('e.spieler1_2', '?1'),
                        $qb->expr()->eq('e.spieler1_3', '?1'),
                        $qb->expr()->eq('e.spieler2_1', '?1'),
                        $qb->expr()->eq('e.spieler2_2', '?1'),
                        $qb->expr()->eq('e.spieler2_3', '?1'),
                        $qb->expr()->eq('e.ersatz1', '?1'),
                        $qb->expr()->eq('e.ersatz2', '?1')
                ))
               ->setParameter(1, $spieler->getId())
        ;

        return $qb->getQuery()->getResult();
    }

}
