<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModusRepository extends EntityRepository
{
    
}
