<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModusRundenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModusRundenRepository extends EntityRepository
{
}
