<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpielRundeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpielRundeRepository extends EntityRepository
{
    public function findBySpieltagOrdered(Spieltag $spieltag)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM LiganetCoreBundle:SpielRunde r WHERE r.spieltag='.$spieltag->getId()." ORDER BY r.nummer ASC ")
            ->getResult();
    }
    
    public function findByLigaSaisonOrdered(LigaSaison $ligasaison)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM LiganetCoreBundle:SpielRunde r JOIN r.spieltag s WHERE s.ligasaison='.$ligasaison->getId()." ORDER BY r.nummer ASC ")
            ->getResult();
    }
}
