<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpielArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpielArtRepository extends EntityRepository
{
    public function findAll()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
                ->from('AppBundle:SpielArt', 's')
                ->orderBy('s.nummer');

        return $qb->getQuery()->getResult();
    }
    
    public function findByModusOrdered(Modus $modus)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT sa FROM AppBundle:SpielArt sa WHERE sa.modus='.$modus->getId()."ORDER BY sa.nummer ASC")
            ->getResult();
    }
}
