<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TabelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabelleRepository extends EntityRepository
{
    public function findByRunde($id_spielrunde) {
        return $this->getEntityManager()
            ->createQuery("SELECT t FROM AppBundle:Tabelle t WHERE t.spielrunde=".$id_spielrunde." ORDER BY t.rang ASC ")
            ->getResult();
        
    }
    
    public function findByRundeArray($id_spielrunde) {
        return $this->getEntityManager()
            ->createQuery("SELECT t FROM AppBundle:Tabelle t WHERE t.spielrunde=".$id_spielrunde." ORDER BY t.rang ASC ")
            ->getArrayResult();
        
    }
    
    
}
