imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } 
    default_locale:  %locale%
    #trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
    assets: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'
        - BraincraftedBootstrapBundle:Form:bootstrap.html.twig
    globals:
        gittag: v2.2.1

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            extern:
                driver:   "%database2_driver%"
                host:     "%database2_host%"
                port:     "%database2_port%"
                dbname:   "%database2_name%"
                user:     "%database2_user%"
                password: "%database2_password%"
                charset:  UTF8

    orm:
        default_entity_manager:   default
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                connection:       default
                mappings:
                    AppBundle:
                        type:     annotation  
                        dir:      Entity      
                        prefix:   AppBundle\Entity
            extern:
                connection:       extern
                mappings:
                    AppBundle:
                        type: annotation
                        dir: Entity
                        prefix: AppBundle\Entity

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    #auth_mode: %mailer_login%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address:        admin@liga-net.de
        sender_name:    Liganet
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: FOSUserBundle:Resetting:email.txt.twig 
    registration:
        confirmation:
            enabled:    true

vich_uploader:
    db_driver: orm
    
    mappings:
        verband_image:
            uri_prefix:         /images/verband
            upload_destination: %kernel.root_dir%/../web/images/verband
        verein_image:
            uri_prefix:         /images/verein
            upload_destination: %kernel.root_dir%/../web/images/verein
        region_image:
            uri_prefix:         /images/region
            upload_destination: %kernel.root_dir%/../web/images/region
