_home:
    pattern:  /
    defaults: { _controller: LiganetCoreBundle:Home:index }
#hello:
#    pattern:  /hello/{name}
#    defaults: { _controller: LiganetCoreBundle:Hello:index }
hello_showUsers:
    pattern:  /hello/showUsers
    defaults: { _controller: LiganetCoreBundle:Hello:showUsers }
verband:
    pattern:  /verband
    defaults: { _controller: LiganetCoreBundle:Verband:index }
verband_show:
    pattern:  /verband/show/{id}
    defaults: { _controller: LiganetCoreBundle:Verband:show }
verband_add:
    pattern:  /verband/add
    defaults: { _controller: LiganetCoreBundle:Verband:add }
region:
    pattern:  /region
    defaults: { _controller: LiganetCoreBundle:Region:index }
region_show:
    pattern:  /region/show/{id}
    defaults: { _controller: LiganetCoreBundle:Region:show }
region_add:
    pattern:  /region/add/{id}
    defaults: { _controller: LiganetCoreBundle:Region:add, id: 0 }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
