security:
  
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CAPTAIN:     ROLE_USER
        ROLE_CLUB_MANAGEMENT:  ROLE_CAPTAIN
        ROLE_LEAGUE_MANAGEMENT: ROLE_CLUB_MANAGEMENT
        ROLE_REGION_MANAGEMENT: ROLE_LEAGUE_MANAGEMENT
        ROLE_UNION_MANAGEMENT:  ROLE_REGION_MANAGEMENT
        ROLE_ADMIN:       ROLE_UNION_MANAGEMENT
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            form_login:
                login_path: /login
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^.*/xml, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^.*/json, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ligasaison/extern/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/spieltag/extern/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/img/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/uploads/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        