services:
    app.verein_voter:
        class: AppBundle\Security\VereinVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
