services:
#fix
    fos_user.doctrine_registry:
        alias: doctrine
#Voters
    app.verein_voter:
        class: AppBundle\Security\VereinVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    app.mannschaft_voter:
        class: AppBundle\Security\MannschaftVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    app.mannschaftspieler_voter:
        class: AppBundle\Security\MannschaftSpielerVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    app.spieler_voter:
        class: AppBundle\Security\SpielerVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    app.ligasaison_voter:
        class: AppBundle\Security\LigaSaisonVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    app.liga_voter:
        class: AppBundle\Security\LigaVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    app.spieltag_voter:
        class: AppBundle\Security\SpieltagVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    app.spielrunde_voter:
        class: AppBundle\Security\SpielRundeVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

#Utils
    app.util.losung:
        class: AppBundle\Util\LosenService
        arguments: ["@doctrine.orm.entity_manager"]
    app.util.platzlosung:
        class: AppBundle\Util\PlatzLosenService
        arguments: ["@doctrine.orm.entity_manager"]
    app.util.xmlErgebnisse:
        class: AppBundle\Util\xmlErgebnisseService
        arguments: ["@doctrine.orm.entity_manager"]
    app.util.berechnenErgebnis:
        class: AppBundle\Util\berechnenErgebnisService
        arguments: ["@doctrine.orm.entity_manager"]
    app.util.pdf.spielberichtsbogen:
        class: AppBundle\Util\pdfSpielberichtsbogenService
        arguments: ["@doctrine.orm.entity_manager", "@white_october.tcpdf"]
    app.util.pdf.spielermeldebogen:
        class: AppBundle\Util\pdfSpielermeldebogenService
        arguments: ["@doctrine.orm.entity_manager", "@white_october.tcpdf"]
    app.util.pdf.spielplan:
        class: AppBundle\Util\pdfSpielplanService
        arguments: ["@doctrine.orm.entity_manager", "@white_october.tcpdf"]
    app.util.excel.spieltag:
        class: AppBundle\Util\excelSpieltagErgebnisseService
        arguments: ["@doctrine.orm.entity_manager"]    
    app.util.sync.verein:
        class: AppBundle\Util\VereinSync
        arguments: ["@doctrine", "@doctrine.orm.entity_manager", "@doctrine.orm.extern_entity_manager"]    
    app.util.sync.spieler:
        class: AppBundle\Util\SpielerSync
        arguments: ["@doctrine", "@doctrine.orm.entity_manager", "@doctrine.orm.extern_entity_manager"]  
