liganet_core_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LiganetCoreBundle:Default:index }

hello_showUsers:
    pattern:  /hello/showUsers
    defaults: { _controller: LiganetCoreBundle:Hello:showUsers }
    
admin_index:
    pattern:  /admin
    defaults: { _controller: LiganetCoreBundle:Admin:index }
admin_edit:
    pattern:  /admin/edit/{id}
    defaults: { _controller: LiganetCoreBundle:Admin:edit }
admin_clear_cache:
    pattern:  /admin/clear_cache
    defaults: { _controller: LiganetCoreBundle:Admin:clearCache }

