hello_showUsers:
    path:  /hello/showUsers
    defaults: { _controller: LiganetCoreBundle:Hello:showUsers }
    
admin_index:
    path:  /admin
    defaults: { _controller: LiganetCoreBundle:Admin:index }
admin_edit:
    path:  /admin/edit/{id}
    defaults: { _controller: LiganetCoreBundle:Admin:edit }
admin_clear_cache:
    path:  /admin/clear_cache
    defaults: { _controller: LiganetCoreBundle:Admin:clearCache }

