parameters:
    liganet_core.losung.class: Liganet\CoreBundle\Services\LosenService

services:
#    liganet_core.example:
#        class: %liganet_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    liganet_core.losung:
        class:  %liganet_core.losung.class%
        arguments: ["@doctrine.orm.entity_manager"]
