parameters:
#    liganet_core.example.class: Liganet\CoreBundle\Example

services:
#    liganet_core.example:
#        class: %liganet_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
