parameters:
    liganet_core.losung.class: Liganet\CoreBundle\Services\LosenService
    liganet_core.platzlosung.class: Liganet\CoreBundle\Services\PlatzLosenService
    liganet_core.xmlErgebnisse.class: Liganet\CoreBundle\Services\xmlErgebnisseService
    liganet_core.pdfSpielberichtsbogen.class: Liganet\CoreBundle\Services\pdfSpielberichtsbogenService
    liganet_core.pdfSpielermeldebogen.class: Liganet\CoreBundle\Services\pdfSpielermeldebogenService
    liganet_core.pdfSpielplan.class: Liganet\CoreBundle\Services\pdfSpielplanService
    liganet_core.berechnenErgebnis.class: Liganet\CoreBundle\Services\berechnenErgebnisService
    liganet_core.excelSpieltagErgebnisse.class: Liganet\CoreBundle\Services\excelSpieltagErgebnisseService

services:
    liganet_core.losung:
        class:  %liganet_core.losung.class%
        arguments: ["@doctrine.orm.entity_manager"]
    liganet_core.platzlosung:
        class:  %liganet_core.platzlosung.class%
        arguments: ["@doctrine.orm.entity_manager"]
    liganet_core.xmlErgebnisse:
        class:  %liganet_core.xmlErgebnisse.class%
        arguments: ["@doctrine.orm.entity_manager"]
    liganet_core.berechnenErgebnis:
        class:  %liganet_core.berechnenErgebnis.class%
        arguments: ["@doctrine.orm.entity_manager"]
    liganet_core.pdf.spielberichtsbogen:
        class:  %liganet_core.pdfSpielberichtsbogen.class%
        arguments: ["@doctrine.orm.entity_manager", "@white_october.tcpdf"]
    liganet_core.pdf.spielermeldebogen:
        class:  %liganet_core.pdfSpielermeldebogen.class%
        arguments: ["@doctrine.orm.entity_manager", "@white_october.tcpdf"]
    liganet_core.pdf.spielplan:
        class:  %liganet_core.pdfSpielplan.class%
        arguments: ["@doctrine.orm.entity_manager", "@white_october.tcpdf"]
    liganet_core.excel.spieltag:
        class:  %liganet_core.excelSpieltagErgebnisse.class%
        arguments: ["@doctrine.orm.entity_manager"]    