## YAML Template.
Liganet\CoreBundle\Entity\Ergebnis:
    properties:
        kugeln1:
            - Range:
                min: 0
                max: 13
                minMessage: Du musst mindestens 0 eintragen
                maxMessage: Du darfst maximal 13 eintragen
        kugeln2:
            - Range:
                min: 0
                max: 13
                minMessage: Du musst mindestens 0 eintragen
                maxMessage: Du darfst maximal 13 eintragen
Liganet\CoreBundle\Entity\Begegnung:
    properties:
        ergebnisse:
            - Valid: ~
