<?php

namespace Liganet\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ErgebnisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErgebnisRepository extends EntityRepository
{
    public function findByBegegnungOrdered(Begegnung $begegnung)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT e FROM LiganetCoreBundle:Ergebnis e 
                JOIN e.spielArt sa
                WHERE e.begegnung='.$begegnung->getId()." ORDER BY sa.nummer ASC")
            ->getResult();
    }
}
