<?php

namespace Liganet\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpielArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpielArtRepository extends EntityRepository
{
}
