<?php

namespace Liganet\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpieltagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpieltagRepository extends EntityRepository
{
    public function findByLigaSaisonOrdered(LigaSaison $ligasaison)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s FROM LiganetCoreBundle:Spieltag s WHERE s.ligasaison='.$ligasaison->getId()."ORDER BY s.nummer ASC")
            ->getResult();
    }
}
